name: Build and Test Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          APP_NAME=mywebapp
          VERSION=INSECURE
          docker build -t $APP_NAME:$VERSION .

      - name: Remove old Docker container
        run: |
          APP_NAME=mywebapp
          docker rm -f $APP_NAME || true

      - name: Docker Scout CVEs Check
        run: |
          APP_NAME=mywebapp
          VERSION=INSECURE
          docker scout cves $APP_NAME:$VERSION --output ./vulns.report
          docker scout cves $APP_NAME:$VERSION --only-severity critical --exit-code

      - name: Generate SBOM
        run: |
          APP_NAME=mywebapp
          VERSION=INSECURE
          docker scout sbom --output $APP_NAME.sbom $APP_NAME:$VERSION

      - name: Run Docker Container
        run: |
          APP_NAME=mywebapp
          VERSION=INSECURE
          docker run -d -p 80:80 --name $APP_NAME $APP_NAME:$VERSION
